#!/bin/sh
#

################################################################################
# <®> Copyright
################################################################################
#
#     rmDUY 
#           Este script descarga desde una dirección URL un archivo de video
#           que luego sube mediante las APIs de google a YouTube.
#
#     Copyright (C) 2018 Ricardo MONLA <rmonla@gmail.com>
#
#     Permission is hereby granted, free of charge, to any person
#     obtaining a copy of this file (the "Program"), to deal in the
#     Program without restriction, including without limitation the
#     rights to use, copy, modify, merge, publish, distribute,
#     sublicense, and/or sell copies of the Program, and to permit
#     persons to whom the Program is furnished to do so, subject to
#     the following conditions: The above copyright notice and this
#     permission notice shall be included in all copies or substantial
#     portions of the Program.
#
#     THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#     EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#     OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#     NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#     HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#     FROM, OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR
#     OTHER DEALINGS IN THE PROGRAM.
#
################################################################################
# <®> REQUERIDO
################################################################################
#
#   Este proyecto esta desarrollado para linux y para funcionar 
#   nesecita tener instalado lo siguiente: 
# 
# 	Módulos de linux:
#    	sudo apt-get install wget
# 
# 	Módulos de python:
#    	pip para instalar paquetes python.
#       	--> sudo apt-get install python-pip
#    	google apis para la subida a youtube.
#       	--> sudo pip install --upgrade oauth2client
#       	--> sudo pip install --upgrade google-api-python-client
#
################################################################################
# <®> VARIABLES
################################################################################
 
duyAPP=`basename "$0"`
duyPTH=`dirname "$0"`

duyVER="1.190415"

duyCOP="${duyAPP} v${duyVER} - Copyright (c) 2019 Ricardo MONLA <rmonla@gmail.com>"

duyURL=""
duyARCH=""
duyTIT=""
duyDST=""

duyDST="/tmp/"

################################################################################
# <®> FUNSIONES <®>
################################################################################

duy_ver(){ # <®> Muestra detalle de versión.

  ### Pendiente:
  #### Generar logs de descarga.

  cat >&2 <<EOF

  ${duyAPP} v${duyVER}

  v1.190415 
  * #### Agrega descripción del video para YouTube.
  v1.0.7 
  * #### Se agrega Copyright.
  * #### Se limpia, ordena y optimiza código.
  * #### Se mejora ayuda de modo de uso. 
  * #### Se mejora salidas por pantallas. 
  * #### Se agrega duy_ver() para mostrar detalles de versión.
  * #### Se optimiza CAPTURA DE ARGUMENTOS.
  * #### Se actualiza README.md

EOF
	return 0
}

duy_uso(){ # <®> Muestra la forma de uso.
  cat >&2 <<EOF

  Uso:     ${duyAPP} -u URL -a ARCHIVO [OPCIONES]

    Este script descarga desde una dirección URL un archivo de video
    que luego sube mediante las APIs de google a YouTube.

    -u, --url URL             Url del archivo de video a descargar.
    -a, --archivo ARCHIVO     Nombre del archivo descargado.

    -t, --titulo  TITULO      YouTube -> Título.
    -D, --descrip DESCRIPCION YouTube -> Descripción.
    -d, --destino DIRECTORIO  Directorio donde se descarga el archivo [$duyDST].
    -v, --ver                 Muestra detalle de versión.
    -h, --help                Esta ayuda por pantalla.

  Ejemplo: ${duyAPP} -u http://190.114.222.202/tcs/download/EA552BC8-CB22-4E08-9222-21DAAD0CAF3 -a NOMBREvideo -t TITULOvideo
EOF
	return 0
}

duy_run(){ # <®> Ejecuto el script.

	cd $duyPTH 
	
	if [ "${duyTIT}" = "" ]; then
		duyTIT=$duyARCH
	fi

	duyDST2="$duyDST$duyARCH"

	##
	## Verifica si el script es ejecutable.
	##
	if [ ! -x "$duyAPP" ]
	then
		duy_msj -m "No puede ejecutarce el script --> $duyAPP" -s
	fi
	##
	## Ejecuto el script.
	##
	echo
	echo "App            -> $duyAPP"
	echo "Url         [-u]-> $duyURL"
	echo "Archivo     [-a]-> $duyARCH"
	echo "Título      [-t]-> $duyTIT"
	echo "Descripción [-D]-> $duyDSC"
	echo
	echo "Directorio  [-d]-> $duyDST"
	
	echo
	duy_down

	duy_up
	echo

	# python rmDUYTube.py -u "$duyURL" -o "$duyARCH" -t "$duyTIT"
	
	duy_exit
	
	exit 1
}

duy_msj(){ # <®> Muestra un mensajes por pantalla.

	# -m MENSAJE  Mensaje a mostrar.
	# -u	      Muestra uso del script.
	# -v	      Muestra detalle de versión.
	# -s	      Sale del script.
	
	msj=''
	sale=0

	## Argumentos.
	while [ "$1" ]; do
	    case "$1" in
		-m)
			shift
		    msj="$1"
		    ;;
		-u) 
		    duy_uso
		    ;;
		-v) 
		    duy_ver
		    ;;
		-s)
		    sale=1
		    ;;
	    esac
	    shift
	done

	## Muestra el mensaje.
	if [ "$msj" != "" ]; then
		echo ""
		echo ""
		echo "$duyAPP: $msj"
	fi 

	## Sale del script.
	if [ $sale = 1 ]; then
		echo "################################################################################"
		echo ""
		exit 1
	else
		return 0
	fi
}

duy_exit(){ # <®> Sale del script.
	duy_msj  -s -m "Todos los procesos terminados."
	return 0
}

duy_down(){ # <®> Descarga el archivo desde la url.
	dst="$duyDST2"
	url="$duyURL"

	echo
	wget -O "$dst" "$url"
	
	return 0
}

duy_up(){ # <®> Subo el archivo a YouTube.
	file="$duyDST2"
	tit="$duyTIT"
	dsc="$duyDSC"

	echo
	python rmDUY_UP.py --file="$file" --title="$tit" --description="$dsc"
	
	return 0
}

################################################################################
# <®> CAPTURA DE ARGUMENTOS <®>
################################################################################

clear
echo ""
echo "################################################################################"
echo "#   <®>${duyCOP}<®>   #"   
echo "################################################################################"

while [ $# -gt 0 ]
do
	case $1 in
		-u | --url)
			duyURL=$2;
			if [ "${duyURL}" = "" ]; then
				duy_msj -u -s -m "Falta URL --> -u URL"
			else
				shift 2
			fi
			;;
		-a | --archivo)
			duyARCH=$2;
			if [ "${duyARCH}" = "" ]; then
				duy_msj -u -s -m "Falta nombre del ARCHIVO de salida --> -a ARCHIVO"
			else
				shift 2
			fi
			;;
		-t | --titulo)
			duyTIT=$2;
			if [ "${duyTIT}" = "" ]; then
				duyTIT=$duyARCH
			else
				shift 2
			fi
			;;
		-D | --descrip)
			duyDSC=$2;
			if [ "${duyDSC}" = "" ]; then
				duyDSC=$duyARCH
			else
				shift 2
			fi
			;;
		-d | --destino)
			destino=$2;
			if [ -d "${destino}" ]; then
				duy_msj -m "Directorio invalido se opta por predeterminado [${duyDST}]"
			else
				duyDST=$destino
			fi
			shift 2
			;;
		-v | --ver)
			duy_msj -v -s
			;;
		-h | --help)
			duy_msj -u -s
			;;
		*)
			duy_msj  -u -s -m "No se reconoce el parámetro --> $1"
			break;
			;;
	esac
done
      

################################################################################
# <®> VERIFICACION Y EJECUCION <®>
################################################################################

if [ "${duyURL}" = "" ] || [ "${duyARCH}" = "" ] ; then
	duy_msj -u -s -m "Faltan parámetros."
else
	duy_run ${1+"$@"}
fi
	
exit 1

